apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - name: hello-world
    port: 8888
    protocol: TCP
    nodePort: 30080 
  selector:
    app: hello-world